name = "sojo-boutique-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "sojo-boutique-db"
database_id = "bbfa58fa-4977-4547-b856-55c40f45e922"

# Cloudflare R2 Bucket
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "soho-boutique-images"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "tu_clave_secreta_super_segura_cambiar_en_produccion"
